### ISSUE TITLE
Additional points to be documented in the contributing guide

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/documentation#74]
This task is meant to collect the additional points to be documented in the contributing guide:
- [x] using web interface or `git rebase` to merge changes from the upstream repository in case it was updated since the feature branch creation
- [x] using alerts/info messages, see https://docs.egi.eu/users/cloud-compute/faq/#how-can-i-inject-my-public-ssh-key-into-the-machine
- [x] including images (code snippet + naming of files), 
- [x] including code snippets
- [x] README should also propose to use the live/nice version at https://docs.egi.eu/about/contributing/
- [x] using `git stash` to backup changes uncommitted made to master, creating a feature branch and committing changes
- [x] ensuring to save/commit quickly changes made to a PR via the web interface to avoid problems like https://github.com/EGI-Foundation/documentation/pull/77#issuecomment-708385531
- [x] Style/contributing guide should clarify how services should be named (complete portfolio name) and acronyms used (only when providing a clear benefit and not for service n ames) (see https://github.com/EGI-Foundation/documentation/pull/83#issuecomment-709893461)
- [x] A link to style rules can be added to the pull request template

**Comment by gwarf** [comment]
@andrea-manzi , @enolfc do you see additional points that would be worth to be covered?
I will try to address them all at once to avoid doing more mini-PRs.

**Comment by andrea-manzi** [comment]
maybe we can add a section to explain how to propose new sections to be added? Opening a ticket or do a PR?

**Comment by gwarf** [comment]
> maybe we can add a section to explain how to propose new sections to be added? Opening a ticket or do a PR?

So it may be something done via a description of the structure: as we don't expect section to be included if they don't fall under the organisation we discussed, ie service-centric, with a section per service.
I also plan to add placeholders for all services that needs to be documented, ideally pointing to their actual documentation so that at least we have something.
We can say that more generically it's advised to open an issue to discuss/propose things, ideally before making a PR, especially/at least for for important changes.

**Comment by gwarf** [comment]
Should we enforce/advocate using a link to the egi.eu service page when naming services?
Like
```markdown
[EGI High Throughput Compute](https://www.egi.eu/services/high-throughput-compute/)
```

See https://github.com/EGI-Foundation/documentation/pull/83#issuecomment-709921960.
