### ISSUE TITLE
Complete move of DataHub documentation

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/documentation#90]
We should ensure that documentation in wiki.egi.eu has been moved here (if relevant) and properly marked as obsolete.

List of pages to move/obsolete/replace:

https://wiki.egi.eu/wiki/EGI_Opendata_platform

Initial issue was https://github.com/EGI-Foundation/datahub-documentation/issues/5

**Comment by andrea-manzi** [comment]
Looks that everything is there.  i'm not going to document how to create a VM to host a oneprovider as this should be already covered elsewhere

**Comment by gwarf** [comment]
@andrea-manzi  please deprecate https://wiki.egi.eu/wiki/EGI_Opendata_platform, you can use the following wiki template: https://wiki.egi.eu/wiki/Template:DeprecatedAndMovedTo

**Comment by andrea-manzi** [comment]
ops sorry, i just added the deprecation warning
